"""
Defines configuration constants for paths and directories used in the analytics module.
"""
from __future__ import annotations

import os
from pathlib import Path

ORG = os.getenv("GITHUB_ORG", "hiero-ledger")
REPO = os.getenv("GITHUB_REPO", "hiero-sdk-python")

"""
PROJECT_ROOT is the root directory of the project, calculated as three levels up from this file's location.
OUTPUTS_DIR is the main directory for all outputs generated by the analytics module, including data files and charts.
DATA_DIR is the subdirectory within OUTPUTS_DIR where all data files (e.g., CSVs, JSONs) will be stored.
CHARTS_DIR is the subdirectory within OUTPUTS_DIR where all generated charts (e.g., PNGs, SVGs) will be saved.
"""
PROJECT_ROOT = Path(__file__).resolve().parents[3]
SRC = PROJECT_ROOT / "src" / "hiero_analytics"

OUTPUTS_DIR = PROJECT_ROOT / "outputs"

DATA_DIR = OUTPUTS_DIR / "data"
CHARTS_DIR = OUTPUTS_DIR / "charts"

REPO_DATA_DIR = DATA_DIR / "repo"
ORG_DATA_DIR = DATA_DIR / "org"

REPO_CHARTS_DIR = CHARTS_DIR / "repo"
ORG_CHARTS_DIR = CHARTS_DIR / "org"

def ensure_output_dirs() -> None:
    """
    Ensure the above directories exist.
    Should be called by runner scripts before writing files to ensure they can be saved to that location
    
    Args:
        None
    Returns:
        None
    """
    for path in [
        OUTPUTS_DIR,
        DATA_DIR,
        CHARTS_DIR,
        REPO_DATA_DIR,
        ORG_DATA_DIR,
        REPO_CHARTS_DIR,
        ORG_CHARTS_DIR,
    ]:
        path.mkdir(parents=True, exist_ok=True)

def ensure_org_dirs(org: str) -> tuple[Path, Path]:
    """
    Create org-specific output directories.
    Args:
        org: Organization identifier, such as a GitHub organization name or slug.
    Returns:
        A tuple containing:
            org_data_dir: Directory for organization-level data outputs.
            org_charts_dir: Directory for organization-level chart outputs.
    """
    org_name = org.replace("/", "_")

    org_data_dir = ORG_DATA_DIR / org_name
    org_charts_dir = ORG_CHARTS_DIR / org_name

    org_data_dir.mkdir(parents=True, exist_ok=True)
    org_charts_dir.mkdir(parents=True, exist_ok=True)

    return org_data_dir, org_charts_dir

def ensure_repo_dirs(repo: str) -> tuple[Path, Path]:
    """
    Create repo-specific output directories.

    Returns:
        repo_data_dir, repo_charts_dir
    """
    repo_name = repo.replace("/", "_")

    repo_data_dir = REPO_DATA_DIR / repo_name
    repo_charts_dir = REPO_CHARTS_DIR / repo_name

    repo_data_dir.mkdir(parents=True, exist_ok=True)
    repo_charts_dir.mkdir(parents=True, exist_ok=True)

    return repo_data_dir, repo_charts_dir

_query_cache: dict[str, str] = {}

def load_query(query_name: str) -> str:
    """Helper to load query text from the queries directory."""
    if query_name not in _query_cache:
        query_path = SRC / "data_sources" / "queries" / f"{query_name}.graphql"
        with open(query_path, "r", encoding="utf-8") as f:
            _query_cache[query_name] = f.read()
    return _query_cache[query_name]
