name: ClusterFuzzLite PR fuzzing

permissions:
    contents: read

on:
    pull_request:
        branches: ["main"]


jobs:
    fuzz:
        name: Fuzz Python inputs
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true
        permissions:
          security-events: write


        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
              with:
                egress-policy: audit

            - name: Build fuzzers
              uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  language: python
                  sanitizer: address

            - name: Run fuzzers
              uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                fuzz-seconds: 300
                mode: code-change
                sanitizer: address
                output-sarif: true
